Feature/29/Connected Frontend to Backend
utmgdsc/CarbonTrack pull request #13
Opened 2023-11-03 14:19 UTC by Yazan10x

## Describe your changes

Created Sign Up Endpoint in Flask
Implemented the Generation of Firebase Auth Token to Authenticate User

## Screenshot of the changes

![image](https://github.com/utmgdsc/CarbonTrack/assets/58717488/3cafc843-70fa-4cb5-93e1-67bffb56eee9)

Insert any relevant media that showcases your change.

## Trello ticket number and link

[24](https://trello.com/c/2deHsqqQ)
[29](https://trello.com/c/84jFLBBQ)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have requested for code review from at least one team mate and our mentor
- [ ] I have locally tested my changes and addresesed any bugs
- [ ] All naming standards are followerd (i.e branch, commits, title)
- [ ] I have informed the team via discord that the task is ready for review & appropriately updated Trello

2023-11-06 01:01 UTC, jasmineguru approved these changes

2023-11-06 05:06 UTC, nxabdullah commented on frontend/assets/colorConstants.tsx
> +
Niceeeeee!

2023-11-06 05:15 UTC, nxabdullah requested changes

2023-11-06 05:15 UTC, nxabdullah commented on backend/.venv/pyvenv.cfg
> +command = /opt/homebrew/opt/python@3.11/bin/python3.11 -m venv /Users/jasmineguruparan/Downloads/CarbonTrack/backend/.venv
This file should not be commited, please remove and add it to gitignore @Yazan10x

2023-11-06 05:15 UTC, nxabdullah commented on backend/.venv/pyvenv.cfg
> +command = /opt/homebrew/opt/python@3.11/bin/python3.11 -m venv /Users/jasmineguruparan/Downloads/CarbonTrack/backend/.venv
Remove the `.venv` folder as a whole and add it to gitignore

2023-11-08 01:37 UTC, nxabdullah approved these changes

2023-11-08 03:53 UTC, merged